spring:
  datasource:
    url: jdbc:h2:~/test-holy # H2 데이터베이스를 embedded 모드로 설정
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    hibernate:
      ddl-auto: update # Hibernate의 DDL 자동 생성 전략 (update, create, create-drop 등)
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화
